### ISSUE TITLE
Staging / Mozilla: scroll bar with submenu doesn't look very good

### ISSUE THREAD

**Issue by ArcAnya** [OpenQDev/OpenQ-Frontend#1566] opened 2023-03-04 18:53 UTC
![image](https://user-images.githubusercontent.com/75732239/222923756-eeb73b0e-6b59-4d01-94d9-d9c7bb5b7c75.png)

**Comment by FlacoJones** [comment] 2023-03-05 19:11
Duplicate of https://github.com/OpenQDev/OpenQ-Frontend/issues/1549

**Comment by ArcAnya** [comment] 2023-03-06 04:59
Not exactly - currently the scrollbar will happen on smaller devices, so it's going to keep looking ugly on mozilla even after solving #1549

**Closed as completed** 2023-03-09 15:06 UTC
Labels: Fixed - awaiting merge
