### ISSUE TITLE
Easy Fix: Polygon Exception Call

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1241] opened 2023-01-30 15:31 UTC
Polygon Call Exception
An exception occured while calling Polygon. You might want to try again. If you need more information or want to report a bug, please contact info@openq.dev

I think this happens when you try to create a bounty that was already minted. We should change the error message or just disable the mint contract button (if the bounty is not indexed I think it wont be easy to disable it so we should in that case also change the error message to something like bounty already exists)

**Comment by ArcAnya** [comment] 2023-01-31 10:15
OK, mintbutton is already disabled for contracts that have already been minted - but I'll look into a solution for when the bounty is not indexed yet

**Comment by ArcAnya** [comment] 2023-01-31 11:08
On Staging:

I received the above "Polygon Call Exception" Message when minting **a completely new (just created) issue**. 
I tried minting again and then it worked without error. 
I tried minting a third time right away and then got a different error message:
(Hence the Polygon Exception Call error message must have a different origin - but we've been having this issue since at least autumn I believe, and not able to reproduce it on a consistent basis)

![image](https://user-images.githubusercontent.com/75732239/215743902-1649632c-e9fb-4ce6-b514-9d4e7cc98140.png)

**Comment by ArcAnya** [comment] 2023-01-31 11:54
For first Polygon Exception Call message
![image](https://user-images.githubusercontent.com/75732239/215753072-d6863362-20eb-408d-8f0a-76ba18228469.png)

**Comment by ArcAnya** [comment] 2023-01-31 12:05
https://blog.logrocket.com/understanding-resolving-metamask-error-codes/

ErrorModal response for #32603 seems accurate (need to try again)
https://blog.logrocket.com/understanding-resolving-metamask-error-codes/#32603

I'll look into a better solution for bounties which are being indexed (#1248)

**Closed as completed** 2023-02-03 00:58 UTC
Labels: bug, HIGH PRIORITY, Fixed - awaiting merge
