### ISSUE TITLE
Login/ Logout - Clean up

### ISSUE THREAD

**Issue by rickkdev** [OpenQDev/OpenQ-Frontend#1117] opened 2022-12-20 11:36 UTC
# About

Im going to use the current prod version to give some feedback regarding authentication/ logout/ signup.

In case certain tasks are already completed, just mark them as completed:

## Suggestions

- [x] Currenlty if I enter app.openq.dev for in a private browser I get a for a split second an error message, which then transitions into "Please login with Github." Shouldn't I get redirected to our signup page automatically?

![split second](https://user-images.githubusercontent.com/28826387/208656414-79713ba8-ec82-4281-99ad-edf946455587.gif)

- [x] After login via that model I did not login as a user just authenticated Github:

Why don't we do the main login here?
![this](https://user-images.githubusercontent.com/28826387/208656719-5753556c-87cc-4371-aee8-3c84d1ea2567.png)

- [x] The profile dropdown menu in the navbar should have a Logout option
Same issue: https://github.com/OpenQDev/OpenQ-Frontend/issues/1114

Questions:
- [x] In the profile, if I click on "Sign Out" under Github Connection, it seems like that will log out of my account. Should we redirect the user to the main page again instead of sticking to the profile? It looks strange because they still seem to have options to edit their profile. So it doesn't look like they logged out even though they did

![this](https://user-images.githubusercontent.com/28826387/208657320-16222b62-c64b-4513-93d8-75dbc812a3d7.png)

- [x] It looks like we are not allowing users currently to check out the bounty page without being logged in. Is this intentional? Let's discuss if that's the way to go for now, weighing the pros and cons, especially our GitHub API issues.

**Comment by Christopher-Stevers** [comment] 2022-12-21 23:55
> Currenlty if I enter app.openq.dev for in a private browser I get a for a split second an error message, which then transitions into "Please login with Github." Shouldn't I get redirected to our signup page automatically?
We could make this into a redirect, but the issue we might run into there is users trying to login with email from there. I think a modal that requires github login is the best approach in this case. Not being able to browse without sign in must be an issue with the PATS on production @alo9507  would you be able to update them?

**Comment by Christopher-Stevers** [comment] 2022-12-21 23:57
> After login via that model I did not login as a user just authenticated Github
Wasn't able to confirm this.  @rickkdev were you trying to log in with a github account for the first time?

**Comment by ArcAnya** [comment] 2022-12-22 09:58
I believe the "just authenticated Github" issue was solved (issue #1109) - or are we talking about sthg different here? => if that was the issue, test on staging, it is currently working as intended for me

**Comment by Christopher-Stevers** [comment] 2022-12-22 13:54
I think this is the same - thing, I've marked it as completed here.

**Closed as completed** 2023-02-14 11:10 UTC
Labels: Fixed - awaiting merge
